name: Survivors
version: '${project.version}'
main: com.scaffus.survivors.Survivors
api-version: 1.18
authors: [ Scaffus ]
description: Paper plugin for survivors smp
website: https://www.youtube.com/channel/UC4-uJde_HISRyfOKKtVEkCQ

commands:
  back:
    aliases: [retour]
    description: Téléporte le joueur à son emplacement précédent
  spawn:
    aliases: []
    description: Téléporte le joueur au spawn
    #usage: /spawn [set]
  test:
    description: commande test
    #usage: /test
  reloadconfig:
    aliases: [rlconfig, rlc, reloadc]
    description: Rercharge la config
    #: /rlc, /rlconfig, /reloadc, /reloadconfig
  msg:
    aliases: [message, tell]
    description: Envois de messages privés
    #usage: /msg <target_player> <message>
  r:
    aliases: [repondre, répondre, reply]
    description: Répondre à un message privé
    #usage: /r <message>
  kill:
    aliases: [tuer]
    description: Tue un joueur donné
  mute:
    aliases: [tg]
    description: Rend un joueur donné muet
  unmute:
    aliases: []
    description: Rend la parole à un joueur donné
  tpa:
    aliases: [teleporta]
    description: Teleportation à un joueur donné
  tpaccept:
    aliases: [teleportaccept, teleportaccepte, teleportoui, tpaoui]
    description: Accepte la demande de téléportation
  tpadeny:
    aliases: [teleportdeny, teleportnon, tpanon]
    description: Refuse la demande de téléportation
  money:
    aliases: [balance, bal, argent]
    description: Affiche l'argent du joueur
  pay:
    aliases: [payer]
    description: Paie un joueur donné d'un montant donné